#Define a storage Class
---
apiVersion: storage.k8s.io/v1
kind: StorageClass 
metadata: 
  name: fast-ssd
provisioner: ebs.csi.aws.com
parameters:
  type: gp3
  fsType: ext4
reclaimPolicy: Delete
volumeBindingMode: waitForFirstConsumer

...

# User creats a PVC (auto triggers PV creation)
---
apiVersion: v1 
kind: PersistentVolumeClaim 
metadata:
  name: dynamic-ebs-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: fast-ssd